class STATE:
    MAIN_MENU = 'MAIN_MENU'
    SEARCHING_GAME = 'SEARCHING_GAME'
    DETECTING_SIDE_AND_PICKING_HERO = 'DETECTING_SIDE_AND_PICKING_HERO'
    PLAYING = 'PLAYING'
    START_BUY = 'START_BUY'
    WAITING = 'WAITING'